title = "Jacob Hell"
author = "Jacob Hell"
paginate = 10
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "smol"
rssLimit = 20

[markup.goldmark.renderer]
  unsafe = true

[Author]
  name = "Jacob Hell"

# Parameters
[params]
   # subtitle = "Your blog subtitle goes here!"
    dateFmt = "02.01.2006"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "runs"
        name = "Runs"
        url = "/runs/"
        weight = 2
		
	[[menu.main]]
        identifier = "links"
        name = "Links"
        url = "/links/"
        weight = 3
		
  [[menu.main]]
		identifier = "feed"
        name = "Feed"
        url = "/index.xml"
        weight = 4

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/jacobhell"
        weight = 1 

    [[menu.footer]]
        name = "LinkedIn"
        url = "https://linkedin.com/in/jacobhell"
        weight = 2 