baseURL = "https://jacobhell.github.io/"
title = "Jacob Hell's Blog"
author = "Jacob Hell"
paginate = 10
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "harbor"
rssLimit = 20

[params]
  googleAnalytics = "UA-161403382-1"

[markup.goldmark.renderer]
  unsafe = true

[Author]
  name = "Jacob Hell"

[outputs]
  section = ["JSON", "HTML"]
  
[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3
  
[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3
  
[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "search"
  weight = 3

[[params.nav]]
  identifier = "rss"
  name = "RSS"
  icon = "fas fa-rss"
  url = "/index.xml"
  weight = 3